language: node_js
node_js:
- '0.11'
- '0.10'

install:
  - chmod +x ./install.sh
  - ./install.sh

before_script:
  - git config --global user.email "alxandr@alxandr.me"
  - git config --global user.name "Alxandr (via TravisCI)"

script: mimosa build

deploy:
  provider: npm
  email: alxandr@alxandr.me
  api_key:
    secure: SkjuauBo5wn+QMrfdnWbjGCl6rxKkIH8G37mg6O2gYVSm30c6yaN44IL5JXLB+Jm+0WCXZrtcMOuS9TiUq5bJ4bL6pwg1xPppzKjwxpuyXCWR0bswWn0fTcIeSN3RLSRAY2UflNIUR3tJus2xxNGMWlPAzaPM/xG2YgfIzedcik=
  on:
    tags: true
    repo: YoloDev/mimosa-6to5
    node_js: '0.10'
